[versions]
androidGradlePlugin = "9.0.0"
annotation = "1.9.1"
json = "20250517"
kotlin = "2.2.20"
compose = "1.10.1"
lifecycle = "2.10.0"
material3 = "1.5.0-alpha09"
media3 = "1.9.1"
room = "2.8.4"
hilt = "2.59"
ktor = "3.4.0"
ksp = "2.3.4"
jsoup = "1.22.1"
re2j = "1.8"
coil = "3.3.0"
guava = "33.5.0-jre"
coroutinesGuava = "1.10.2"
concurrentFutures = "1.3.0"
activity = "1.12.2"
navigation = "2.9.6"
hiltNavigation = "1.3.0"
datastore = "1.2.0"
workManager = "2.11.0"
composeReorderable = "3.0.0"
squigglyslider = "1.0.0"
shimmer = "1.3.3"
palette = "1.0.0"
apacheLang3 = "3.20.0"
brotli = "0.1.2"
desugaring = "2.1.5"
junit = "4.13.2"
timber = "5.0.1"
kuromojiIpadic = "0.9.0"
extractor = "2d2d9ed"
rhino = "1.9.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "coroutinesGuava" }
concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFutures" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "composeReorderable" }

squigglyslider = { module = "me.saket.squigglyslider:squigglyslider", version.ref = "squigglyslider" }

viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }

palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }

media3 = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

apache-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheLang3" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
re2j = { module = "com.google.re2j:re2j", version.ref = "re2j" }

json = { module = "org.json:json", version.ref = "json" }

brotli = { module = "org.brotli:dec", version.ref = "brotli" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

junit = { module = "junit:junit", version.ref = "junit" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

#newpipe-extractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version = "v0.25.0" }
#newpipe-extractor = { module = "com.github.libre-tube:NewPipeExtractor", version = "70be3a4" }
newpipe-extractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version = "master-SNAPSHOT" }
#newpipe-extractor = { module = "com.github.mostafaalagamy:MetrolistExtractor", version.ref = "extractor" }

kuromoji-ipadic = { module = "com.atilika.kuromoji:kuromoji-ipadic", version.ref = "kuromojiIpadic" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
